title: SuperInfo Latino (A-H, 2024-25)
description: Una pagina collaborativa con link vari, info esami, e altre risorse varie per il corso di Letteratura latina in unimi.
theme: just-the-docs

aux_links:
  ğŸ§œâ€â™€ï¸ MyAriel del corso: https://myariel.unimi.it/course/view.php?id=3389
  ğŸ“‚ Drive (registrazioni, sbobine, appunti): https://drive.google.com/drive/folders/1wj6Z5NMsjwsVbez0gSmvWLmVyTitCuH2
  â˜‘ï¸ Programma del corso: https://drive.google.com/open?id=1MX1nlZqKeCntUQsTUSzEWd1YC9U5eu-o

callouts:
  warning:
    title: Attenzione
    color: red
  important:
    title: Importante
    color: yellow
  note:
    title: N.B.
    color: blue
